"""Snow Flower v4 mesh builder: geometry in millimetres with PARAMETRIC per-loop UVs.

Every low-poly face carries a local UV in millimetres and an ISLAND id. The atlas packer
(sfv4_uvpack) places each island once; LOD1/LOD2 are generated by the same functions at a
lower resolution with the same island ids and the same local-UV functions, so all three LODs
sample one texture set consistently without any UV transfer.

High-poly (bake source) geometry uses the same builder with island "HIGH" and no packing.
"""
from __future__ import annotations

import math
from typing import Callable, Dict, List, Optional, Sequence, Tuple

import numpy as np

try:
    import bpy  # noqa: F401
    import bmesh  # noqa: F401
    from mathutils import Vector, geometry as mgeo  # noqa: F401
except ImportError:  # pure-python use (tests)
    bpy = None

HIGH = "HIGH"


class MB:
    """Accumulates vertices (mm), faces, per-corner local UVs (mm), island ids and material indices."""

    def __init__(self, name: str):
        self.name = name
        self.verts: List[Tuple[float, float, float]] = []
        self.faces: List[Tuple[int, ...]] = []
        self.fuv: List[Tuple[Tuple[float, float], ...]] = []
        self.fisl: List[str] = []
        self.fmat: List[int] = []

    # ------------------------------------------------------------------ basics
    def v(self, p) -> int:
        self.verts.append((float(p[0]), float(p[1]), float(p[2])))
        return len(self.verts) - 1

    def vs(self, pts) -> List[int]:
        start = len(self.verts)
        for p in pts:
            self.verts.append((float(p[0]), float(p[1]), float(p[2])))
        return list(range(start, len(self.verts)))

    def f(self, idx, uvs=None, island=HIGH, mat=0):
        idx = tuple(int(i) for i in idx)
        if len(set(idx)) < 3:
            return
        if uvs is None:
            uvs = tuple((0.0, 0.0) for _ in idx)
        self.faces.append(idx)
        self.fuv.append(tuple((float(u), float(v)) for u, v in uvs))
        self.fisl.append(island)
        self.fmat.append(int(mat))

    def extend(self, other: "MB"):
        off = len(self.verts)
        self.verts.extend(other.verts)
        for f, uv, isl, m in zip(other.faces, other.fuv, other.fisl, other.fmat):
            self.faces.append(tuple(i + off for i in f))
            self.fuv.append(uv)
            self.fisl.append(isl)
            self.fmat.append(m)

    def tri_count(self) -> int:
        return sum(len(f) - 2 for f in self.faces)

    def islands(self) -> Dict[str, np.ndarray]:
        """Island id -> (N,2) array of every local UV corner of that island."""
        acc: Dict[str, list] = {}
        for uv, isl in zip(self.fuv, self.fisl):
            acc.setdefault(isl, []).extend(uv)
        return {k: np.array(v, float) for k, v in acc.items()}

    def island_areas(self) -> Dict[str, Tuple[float, float]]:
        """Island id -> (3D area mm2, local-UV area mm2)."""
        V = np.array(self.verts, float)
        out: Dict[str, List[float]] = {}
        for f, uv, isl in zip(self.faces, self.fuv, self.fisl):
            p = V[list(f)]
            a3 = 0.0
            au = 0.0
            for k in range(1, len(f) - 1):
                a3 += 0.5 * np.linalg.norm(np.cross(p[k] - p[0], p[k + 1] - p[0]))
                (u0, v0), (u1, v1), (u2, v2) = uv[0], uv[k], uv[k + 1]
                au += 0.5 * abs((u1 - u0) * (v2 - v0) - (u2 - u0) * (v1 - v0))
            o = out.setdefault(isl, [0.0, 0.0])
            o[0] += a3
            o[1] += au
        return {k: (v[0], v[1]) for k, v in out.items()}

    # ------------------------------------------------------------------ Blender
    def to_object(self, name, collection, materials=None, uv_transform=None, smooth_angle=40.0,
                  recalc=True, uv1_transform=None):
        """Create a mesh object (vertices converted mm -> m). ``uv_transform(island, uv_array)`` maps
        local mm UVs to atlas UVs; without it the local UVs are written scaled by 1/1000."""
        import bpy
        import bmesh
        me = bpy.data.meshes.new(name)
        verts = np.array(self.verts, float) * 0.001
        me.from_pydata(verts.tolist(), [], [list(f) for f in self.faces])
        me.update()
        if materials:
            for m in materials:
                me.materials.append(m)
            me.polygons.foreach_set("material_index", self.fmat)
        uvl = me.uv_layers.new(name="UV0")
        loops_uv = np.zeros((len(me.loops), 2), float)
        li = 0
        for fi, (uvs, isl) in enumerate(zip(self.fuv, self.fisl)):
            arr = np.array(uvs, float)
            arr = uv_transform(isl, arr) if uv_transform else arr * 0.001
            n = len(uvs)
            loops_uv[li:li + n] = arr
            li += n
        uvl.data.foreach_set("uv", loops_uv.ravel())
        if uv1_transform is not None:
            uv1 = me.uv_layers.new(name="UV1_Lightmap")
            l1 = np.zeros((len(me.loops), 2), float)
            li = 0
            for fi, (uvs, isl) in enumerate(zip(self.fuv, self.fisl)):
                arr = uv1_transform(isl, np.array(uvs, float))
                n = len(uvs)
                l1[li:li + n] = arr
                li += n
            uv1.data.foreach_set("uv", l1.ravel())
        me.uv_layers.active_index = 0
        if recalc:
            bm = bmesh.new()
            bm.from_mesh(me)
            bmesh.ops.recalc_face_normals(bm, faces=list(bm.faces))
            bm.to_mesh(me)
            bm.free()
        me.polygons.foreach_set("use_smooth", [True] * len(me.polygons))
        if smooth_angle is not None:
            try:
                me.set_sharp_from_angle(angle=math.radians(smooth_angle))
            except Exception:  # noqa: BLE001
                pass
        me.update()
        ob = bpy.data.objects.new(name, me)
        collection.objects.link(ob)
        return ob


# ====================================================================== helpers

def _norm(v):
    v = np.asarray(v, float)
    n = np.linalg.norm(v)
    return v / n if n > 1e-12 else v


def arclen(pts, closed=False):
    pts = np.asarray(pts, float)
    d = np.linalg.norm(np.diff(pts, axis=0), axis=1)
    out = np.concatenate([[0.0], np.cumsum(d)])
    if closed:
        out = np.concatenate([out, [out[-1] + np.linalg.norm(pts[0] - pts[-1])]])
    return out


def catmull(points, steps=6, closed=False):
    """Interpolating Catmull-Rom polyline through ``points``."""
    p = [np.asarray(q, float) for q in points]
    n = len(p)
    out = []
    rng = range(n) if closed else range(n - 1)
    for i in rng:
        a = p[(i - 1) % n] if closed else p[max(i - 1, 0)]
        b = p[i]
        c = p[(i + 1) % n] if closed else p[i + 1]
        d = p[(i + 2) % n] if closed else p[min(i + 2, n - 1)]
        for j in range(steps):
            t = j / steps
            out.append(0.5 * ((2 * b) + (-a + c) * t + (2 * a - 5 * b + 4 * c - d) * t * t
                              + (-a + 3 * b - 3 * c + d) * t ** 3))
    if not closed:
        out.append(p[-1])
    return np.array(out)


def resample(pts, n, closed=False):
    """Resample a polyline to ``n`` points evenly by arclength."""
    pts = np.asarray(pts, float)
    if closed:
        pts = np.vstack([pts, pts[:1]])
    s = arclen(pts)
    targets = np.linspace(0, s[-1], n + (1 if closed else 0))
    out = np.stack([np.interp(targets, s, pts[:, k]) for k in range(pts.shape[1])], 1)
    return out[:-1] if closed else out


# ====================================================================== grid / loft

def grid(mb: MB, P: np.ndarray, closed_c: bool, island: str, mat: int = 0, uv=None, flip=False,
         close_ends: Tuple[Optional[np.ndarray], Optional[np.ndarray]] = (None, None)):
    """Quads between rows of points P[r, c]. ``uv`` (r, c(+1 when closed), 2) local mm or None for
    per-row arclength (u) x row-centroid distance (v). Returns the vertex index array (r, c)."""
    P = np.asarray(P, float)
    nr, nc = P.shape[:2]
    idx = np.array(mb.vs(P.reshape(-1, 3))).reshape(nr, nc)
    if uv is None:
        uv = auto_uv(P, closed_c)
    ncols = nc if closed_c else nc - 1
    for r in range(nr - 1):
        isl = island(r) if callable(island) else island
        for c in range(ncols):
            c2 = (c + 1) % nc
            q = [idx[r, c], idx[r, c2], idx[r + 1, c2], idx[r + 1, c]]
            u = [uv[r, c], uv[r, c + 1], uv[r + 1, c + 1], uv[r + 1, c]]
            if flip:
                q = q[::-1]
                u = u[::-1]
            mb.f(q, u, isl, mat)
    return idx


def auto_uv(P, closed_c):
    P = np.asarray(P, float)
    nr, nc = P.shape[:2]
    cols = nc + 1 if closed_c else nc
    uv = np.zeros((nr, cols, 2))
    cent = P.mean(axis=1)
    vv = arclen(cent)
    for r in range(nr):
        s = arclen(P[r], closed=closed_c)
        mid = s[-1] * 0.5
        uv[r, :, 0] = s - mid
        uv[r, :, 1] = vv[r]
    return uv


def fan_cap(mb: MB, ring_idx: Sequence[int], center, island, mat=0, uv_ring=None, uv_center=None, flip=False):
    c = mb.v(center)
    n = len(ring_idx)
    for i in range(n):
        j = (i + 1) % n
        q = [c, ring_idx[i], ring_idx[j]]
        u = [uv_center, uv_ring[i], uv_ring[j]] if uv_ring is not None else None
        if flip:
            q = q[::-1]
            u = u[::-1] if u else None
        mb.f(q, u, island, mat)
    return c


def planar_uv(pts, origin, U, V):
    d = np.asarray(pts, float) - np.asarray(origin, float)
    return np.stack([d @ np.asarray(U, float), d @ np.asarray(V, float)], -1)


def poly_fill(mb: MB, ring_idx, pts3, uv2, island, mat=0, flip=False):
    """Triangulate a (possibly concave) planar-ish polygon given its vertices and 2D coords."""
    from mathutils import Vector, geometry as mgeo
    tris = mgeo.tessellate_polygon([[Vector((float(a), float(b), 0.0)) for a, b in uv2]])
    for t in tris:
        q = [ring_idx[k] for k in t]
        u = [tuple(uv2[k]) for k in t]
        # tessellate_polygon returns an arbitrary winding: orient by the 2D signed area
        (a0, b0), (a1, b1), (a2, b2) = u
        area = (a1 - a0) * (b2 - b0) - (a2 - a0) * (b1 - b0)
        if (area < 0) != flip:
            q = q[::-1]
            u = u[::-1]
        mb.f(q, u, island, mat)


# ====================================================================== tube

def frames(path):
    """Parallel-transport frames along a polyline: tangents T, normals N, binormals B."""
    P = np.asarray(path, float)
    n = len(P)
    T = np.zeros_like(P)
    for i in range(n):
        a = P[max(i - 1, 0)]
        b = P[min(i + 1, n - 1)]
        T[i] = _norm(b - a)
    N = np.zeros_like(P)
    ref = np.array([0.0, 1.0, 0.0]) if abs(T[0][1]) < 0.9 else np.array([1.0, 0.0, 0.0])
    N[0] = _norm(np.cross(T[0], ref))
    for i in range(1, n):
        v = N[i - 1] - T[i] * np.dot(N[i - 1], T[i])
        N[i] = _norm(v) if np.linalg.norm(v) > 1e-9 else N[i - 1]
    B = np.cross(T, N)
    return T, N, B


def tube(mb: MB, path, radius, sides=6, island=HIGH, mat=0, cap=("flat", "flat"), squash=1.0,
         up=None, closed=False):
    """Sweep a (possibly squashed) circle along ``path``. ``radius`` scalar, array or callable(t).
    cap: 'flat' | 'point' | None per end. ``up`` optional (n,3) array: the squash axis (relief
    normal), which also fixes the frame so the tube's flat side lies on its substrate."""
    P = np.asarray(path, float)
    n = len(P)
    t = arclen(P)
    tt = t / max(t[-1], 1e-9)
    if callable(radius):
        R = np.array([radius(x) for x in tt])
    else:
        R = np.broadcast_to(np.asarray(radius, float), (n,)).copy()
    T, N, B = frames(P)
    if up is not None:
        U = np.asarray(up, float)
        U = np.broadcast_to(U, P.shape) if U.ndim == 1 else U
        N = np.array([_norm(U[i] - T[i] * np.dot(U[i], T[i])) for i in range(n)])
        B = np.cross(T, N)
    ang = np.linspace(0, 2 * math.pi, sides, endpoint=False) + math.pi / sides
    rows = []
    keep = list(range(n))
    tip_start = cap[0] == "point"
    tip_end = cap[1] == "point"
    body = keep[1:] if tip_start else keep
    body = body[:-1] if tip_end else body
    for i in body:
        ring = [P[i] + R[i] * (np.cos(a) * B[i] + squash * np.sin(a) * N[i]) for a in ang]
        rows.append(ring)
    rows = np.array(rows)
    circ = 2 * math.pi * max(float(np.mean(R)), 1e-3)
    uv = np.zeros((len(rows), sides + 1, 2))
    for r, i in enumerate(body):
        uv[r, :, 0] = np.linspace(0, circ, sides + 1) - circ / 2
        uv[r, :, 1] = t[i]
    idx = grid(mb, rows, True, island, mat, uv=uv)
    isl_of = (lambda r: island(r)) if callable(island) else (lambda r: island)
    # ends
    for end, which in ((0, cap[0]), (1, cap[1])):
        cap_isl = isl_of(0) if end == 0 else isl_of(max(len(rows) - 2, 0))
        ring = idx[0] if end == 0 else idx[-1]
        ruv = uv[0] if end == 0 else uv[-1]
        if which == "point":
            tip = P[0] if end == 0 else P[-1]
            tv = t[0] if end == 0 else t[-1]
            fan_cap(mb, list(ring), tip, cap_isl, mat, uv_ring=[tuple(x) for x in ruv[:-1]],
                    uv_center=(0.0, tv), flip=(end == 0))
        elif which == "flat":
            c = P[body[0]] if end == 0 else P[body[-1]]
            k = body[0] if end == 0 else body[-1]
            ring_uv = [(R[k] * math.cos(a) + circ, R[k] * math.sin(a) + t[k] + (3 * R[k] if end else -3 * R[k]))
                       for a in ang]
            ctr_uv = (circ, t[k] + (3 * R[k] if end else -3 * R[k]))
            fan_cap(mb, list(ring), c, cap_isl, mat, uv_ring=ring_uv, uv_center=ctr_uv, flip=(end == 0))
    return idx


def ellipsoid(mb: MB, center, a, b, c, island=HIGH, mat=0, seg=10, rings=6):
    center = np.asarray(center, float)
    a, b, c = (np.asarray(x, float) for x in (a, b, c))
    rows = []
    for j in range(1, rings):
        phi = math.pi * j / rings
        rows.append([center + math.sin(phi) * (a * math.cos(th) + b * math.sin(th)) + c * math.cos(phi)
                     for th in np.linspace(0, 2 * math.pi, seg, endpoint=False)])
    rows = np.array(rows)
    idx = grid(mb, rows, True, island, mat)
    fan_cap(mb, list(idx[0]), center + c, island, mat, flip=True)
    fan_cap(mb, list(idx[-1]), center - c, island, mat)
    return idx
