"""Katana mesh builder: geometry in millimetres with PARAMETRIC per-corner UVs, island ids, material slots, explicit
sharp edges and per-corner paint attributes.

Adapted copy of the Snow Flower v4 builder idea (Scripts/SnowFlower/v4/sfv4_mesh.py; that file is not imported).
Every face carries a local UV in millimetres and an ISLAND id. The atlas packer (katana_uvpack) places each island
once; LOD1/LOD2 are generated by the same functions at a lower resolution with the same island ids and the same
local-UV functions, so all LODs sample one texture set without any UV transfer.

``attr`` per corner (4 floats) carries what the texture painter needs (e.g. the blade's mune-arc station s and its
across distance u; a cord's path length and across offset).
"""
from __future__ import annotations

import math
from typing import Dict, List, Sequence, Tuple

import numpy as np

ZERO4 = (0.0, 0.0, 0.0, 0.0)


class MB:
    def __init__(self, name: str):
        self.name = name
        self.verts: List[Tuple[float, float, float]] = []
        self.faces: List[Tuple[int, ...]] = []
        self.fuv: List[Tuple[Tuple[float, float], ...]] = []
        self.fattr: List[Tuple[Tuple[float, ...], ...]] = []
        self.fisl: List[str] = []
        self.fmat: List[int] = []
        self.sharp: set = set()

    # ------------------------------------------------------------------ basics
    def v(self, p) -> int:
        self.verts.append((float(p[0]), float(p[1]), float(p[2])))
        return len(self.verts) - 1

    def vs(self, pts) -> List[int]:
        start = len(self.verts)
        for p in pts:
            self.verts.append((float(p[0]), float(p[1]), float(p[2])))
        return list(range(start, len(self.verts)))

    def f(self, idx, uvs, island, mat, attrs=None):
        idx = tuple(int(i) for i in idx)
        if len(set(idx)) < 3:
            return
        self.faces.append(idx)
        self.fuv.append(tuple((float(u), float(v)) for u, v in uvs))
        if attrs is None:
            attrs = [ZERO4] * len(idx)
        self.fattr.append(tuple(tuple(float(x) for x in a) + (0.0,) * (4 - len(a)) for a in attrs))
        self.fisl.append(island)
        self.fmat.append(int(mat))

    def mark_sharp(self, a, b):
        self.sharp.add((min(a, b), max(a, b)))

    def extend(self, other: "MB"):
        off = len(self.verts)
        self.verts.extend(other.verts)
        for f, uv, at, isl, m in zip(other.faces, other.fuv, other.fattr, other.fisl, other.fmat):
            self.faces.append(tuple(i + off for i in f))
            self.fuv.append(uv)
            self.fattr.append(at)
            self.fisl.append(isl)
            self.fmat.append(m)
        for a, b in other.sharp:
            self.sharp.add((a + off, b + off))

    def weld(self, tol=1e-4):
        """Merge coincident vertices (e.g. the shared rows where two UV islands of one strip meet). UVs live on the
        corners, so seams survive. Faces that collapse are dropped."""
        V = np.array(self.verts)
        key = np.round(V / tol).astype(np.int64)
        _, first, inv = np.unique(key, axis=0, return_index=True, return_inverse=True)
        inv = inv.ravel()
        remap = first[inv]
        if (remap == np.arange(len(V))).all():
            return 0
        keep = np.unique(remap)
        newidx = -np.ones(len(V), np.int64)
        newidx[keep] = np.arange(len(keep))
        self.verts = [self.verts[i] for i in keep]
        nf, nuv, nat, nisl, nmat = [], [], [], [], []
        for f, uv, at, isl, m in zip(self.faces, self.fuv, self.fattr, self.fisl, self.fmat):
            g = tuple(int(newidx[remap[i]]) for i in f)
            if len(set(g)) < len(g):
                continue
            nf.append(g)
            nuv.append(uv)
            nat.append(at)
            nisl.append(isl)
            nmat.append(m)
        self.faces, self.fuv, self.fattr, self.fisl, self.fmat = nf, nuv, nat, nisl, nmat
        self.sharp = {(min(int(newidx[remap[a]]), int(newidx[remap[b]])), max(int(newidx[remap[a]]), int(newidx[remap[b]])))
                      for a, b in self.sharp}
        return len(V) - len(keep)

    def tri_count(self) -> int:
        return sum(len(f) - 2 for f in self.faces)

    def islands(self) -> Dict[str, np.ndarray]:
        acc: Dict[str, list] = {}
        for uv, isl in zip(self.fuv, self.fisl):
            acc.setdefault(isl, []).extend(uv)
        return {k: np.array(v, float) for k, v in acc.items()}

    def triangles(self):
        """Fan-triangulated corner lists: [(face index, (c0, c1, c2) corner indices)]."""
        out = []
        for fi, f in enumerate(self.faces):
            for k in range(1, len(f) - 1):
                out.append((fi, (0, k, k + 1)))
        return out

    # ------------------------------------------------------------------ Blender
    def to_object(self, name, collection, materials=None, uv_transform=None, uv1_transform=None,
                  smooth_angle=35.0, recalc=False):
        """Mesh object in metres. ``uv_transform(island, uv_array)`` maps local mm UVs to atlas UVs."""
        import bpy
        import bmesh
        me = bpy.data.meshes.new(name)
        verts = np.array(self.verts, float) * 0.001
        me.from_pydata(verts.tolist(), [], [list(f) for f in self.faces])
        me.update()
        if materials:
            for m in materials:
                me.materials.append(m)
            me.polygons.foreach_set("material_index", self.fmat)
        for layer_name, tf in (("UV0", uv_transform), ("UV1_Lightmap", uv1_transform)):
            if layer_name == "UV1_Lightmap" and tf is None:
                continue
            uvl = me.uv_layers.new(name=layer_name)
            loops_uv = np.zeros((len(me.loops), 2), float)
            li = 0
            for uvs, isl in zip(self.fuv, self.fisl):
                arr = np.array(uvs, float)
                arr = tf(isl, arr) if tf else arr * 0.001
                loops_uv[li:li + len(uvs)] = arr
                li += len(uvs)
            uvl.data.foreach_set("uv", loops_uv.ravel())
        me.uv_layers.active_index = 0
        if recalc:
            bm = bmesh.new()
            bm.from_mesh(me)
            bmesh.ops.recalc_face_normals(bm, faces=list(bm.faces))
            bm.to_mesh(me)
            bm.free()
        me.polygons.foreach_set("use_smooth", [True] * len(me.polygons))
        if smooth_angle is not None:
            me.set_sharp_from_angle(angle=math.radians(smooth_angle))
        if self.sharp:
            attr = me.attributes.get("sharp_edge") or me.attributes.new("sharp_edge", "BOOLEAN", "EDGE")
            ev = np.zeros(len(me.edges) * 2, int)
            me.edges.foreach_get("vertices", ev)
            ev = ev.reshape(-1, 2)
            vals = np.zeros(len(me.edges), bool)
            attr.data.foreach_get("value", vals)
            for i, (a, b) in enumerate(ev):
                if (min(a, b), max(a, b)) in self.sharp:
                    vals[i] = True
            attr.data.foreach_set("value", vals)
        me.update()
        ob = bpy.data.objects.new(name, me)
        collection.objects.link(ob)
        return ob


# ====================================================================== helpers

def arclen(pts, closed=False):
    pts = np.asarray(pts, float)
    d = np.linalg.norm(np.diff(pts, axis=0), axis=1)
    out = np.concatenate([[0.0], np.cumsum(d)])
    if closed:
        out = np.concatenate([out, [out[-1] + np.linalg.norm(pts[0] - pts[-1])]])
    return out


def grid(mb: MB, P, closed_c, island, mat, uv, attr=None, flip=False):
    """Quads between rows of points P[r, c] (r along, c around). ``uv``: (r, c(+1 if closed), 2) local mm.
    ``attr``: None or (r, c(+1), 4). Returns the vertex index array (r, c)."""
    P = np.asarray(P, float)
    nr, nc = P.shape[:2]
    idx = np.array(mb.vs(P.reshape(-1, 3))).reshape(nr, nc)
    ncols = nc if closed_c else nc - 1
    for r in range(nr - 1):
        isl = island(r) if callable(island) else island
        for c in range(ncols):
            c2 = (c + 1) % nc
            q = [idx[r, c], idx[r, c2], idx[r + 1, c2], idx[r + 1, c]]
            u = [uv[r, c], uv[r, c + 1], uv[r + 1, c + 1], uv[r + 1, c]]
            a = None if attr is None else [attr[r, c], attr[r, c + 1], attr[r + 1, c + 1], attr[r + 1, c]]
            if flip:
                q, u = q[::-1], u[::-1]
                a = a[::-1] if a is not None else None
            mb.f(q, u, isl, mat, a)
    return idx


def ring_uv(P, closed=True, v_rows=None):
    """Around-arclength (centred) x along-arclength local UV for a loft P[r, c]."""
    P = np.asarray(P, float)
    nr, nc = P.shape[:2]
    cols = nc + 1 if closed else nc
    uv = np.zeros((nr, cols, 2))
    cent = P.mean(axis=1)
    vv = arclen(cent) if v_rows is None else np.asarray(v_rows, float)
    for r in range(nr):
        s = arclen(P[r], closed=closed)
        uv[r, :, 0] = s
        uv[r, :, 1] = vv[r]
    return uv


def profile_loft_uv(P):
    """For a loft whose rows are rings: U = around arclength at the ring of max perimeter (fraction-based, so the
    island is a rectangle-ish), V = arclength of the profile measured at the ring centroids' meridian (true
    distance across the bevels)."""
    P = np.asarray(P, float)
    nr, nc = P.shape[:2]
    frac = np.zeros((nr, nc + 1))
    per = []
    for r in range(nr):
        s = arclen(P[r], closed=True)
        frac[r] = s / max(s[-1], 1e-9)
        per.append(s[-1])
    Pmax = max(per)
    # meridian distance between consecutive rings (mean of vertex-to-vertex distances)
    dv = [0.0] + [float(np.mean(np.linalg.norm(P[r] - P[r - 1], axis=1))) for r in range(1, nr)]
    vv = np.cumsum(dv)
    uv = np.zeros((nr, nc + 1, 2))
    for r in range(nr):
        uv[r, :, 0] = frac[r] * per[r] + (Pmax - per[r]) * 0.5
        uv[r, :, 1] = vv[r]
    return uv


def cap_fill(mb: MB, ring_idx, pts3, uv2, island, mat, flip=False, attrs=None):
    """Triangulate a planar-ish closed ring without a centre vertex (ear clipping on its 2D coords)."""
    from mathutils import Vector, geometry as mgeo
    tris = mgeo.tessellate_polygon([[Vector((float(a), float(b), 0.0)) for a, b in uv2]])
    for t in tris:
        q = [ring_idx[k] for k in t]
        u = [tuple(uv2[k]) for k in t]
        at = None if attrs is None else [attrs[k] for k in t]
        (a0, b0), (a1, b1), (a2, b2) = u
        area = (a1 - a0) * (b2 - b0) - (a2 - a0) * (b1 - b0)
        if (area < 0) != flip:
            q, u = q[::-1], u[::-1]
            at = at[::-1] if at is not None else None
        mb.f(q, u, island, mat, at)


def sweep(mb: MB, rows, island, mat, uv, attr=None):
    """Open strip sweep: rows[r] is a polyline (not closed) -> quads. Same as grid with closed_c False."""
    return grid(mb, rows, False, island, mat, uv, attr)
